# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  config.vm.synced_folder ".", "/vagrant", {
    type: "smb", smb_host: "172.26.96.1", mount_options: ["vers=3.0"],
    smb_username: ENV["VAGRANT_SMB_USERNAME"],
    smb_password: ENV["VAGRANT_SMB_PASSWORD"]
  }

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://vagrantcloud.com/search.
  #config.vm.box = "bento/centos-7.4"
  config.vm.box = "bento/centos-7"
  config.vm.hostname = "pfljenkins01.priv.lab.pfl.net"
  config.vm.network "private_network", type: "dhcp"
  config.vm.provision "shell", inline: <<-SHELL
    yum -y update
    yum -y install wget yum-utils cifs-utils
    curl -fsSL https://get.docker.com/ | sh
    sudo systemctl start docker
    sudo systemctl enable docker
    sudo usermod -aG docker vagrant
    # Setup and run jenkins
    sudo mkdir -p /var/jenkins_home
    sudo chown -R 1000:1000 /var/jenkins_home
    docker volume create jenkins_home
    docker run -p 8080:8080 -p 50000:50000 -v jenkins_home:/var/jenkins_home -d --name jenkins jenkins/jenkins:lts
    sleep 180
    docker exec jenkins cat /var/jenkins_home/secrets/initialAdminPassword
  SHELL

end
